name: Branch Naming Check - Main

on:
  pull_request:
    branches:
      - main

jobs:
  branch-name-validation-main:
    runs-on: ubuntu-latest
    steps:
      - name: check-branch-names
        run: |
          branch_name=${GITHUB_HEAD_REF}
          if [ "$branch_name" == "dev" ]; then
            echo "Branch naming OK"
          else
            echo "Branch naming does not comply with policy - please only merge to main from the dev branch"
            exit 1
          fi
        shell: bash