name: Branch Naming Check - Dev

on:
  workflow_call:

jobs:
  branch-name-validation-dev:
    runs-on: ubuntu-latest
    steps:
      - name: check-branch-names
        run: |
          branch_name=${GITHUB_HEAD_REF}
          if [[ "$branch_name" == feature-* || "$branch_name" == Feature-* || "$branch_name" == docs ]]; then
            echo "Branch naming OK"
          else
            echo "Branch naming does not comply with policy - please prefix feature branch names with 'feature-' or 'docs'"
            exit 1
          fi
        shell: bash


  