name: Test Simple

on: [push, pull_request, workflow_dispatch]

jobs:
  test-simple:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run a single test
        run: pytest github_action_example/tests/test_github_action.py -k test_gh_action2

      - name: Run every test in this .py file
        run: pytest github_action_example/tests/test_github_action.py



